version: '3'  
  
services:  
  gptweb:  
    container_name: GPT_A_WEB  
    image: ydlhero/GPT_A_WEB:latest # 使用latest标签，确保始终获取最新版本  
    ports:  
      - "6050:3002"  
    environment:  
      # 时区设置  
      TZ: Asia/Shanghai  
        
      # OpenAI API 配置  
      OPENAI_API_KEY: sk-xxxx  
      OPENAI_API_BASE_URL:  
      OPENAI_API_MODEL:  
        
      # 访问控制  
      AUTH_SECRET_KEY:  
      API_UPLOADER: "1" # 默认为允许上传  
      HIDE_SERVER: "0" # 默认为不隐藏服务端  
        
      # midjourney 配置  
      MJ_SERVER:  
      MJ_API_SECRET:  
        
      # 自定义模型  
      CUSTOM_MODELS: "-gpt-3.5-turbo-0301,gpt-4.5"  
        
      # 统计分析  
      TJ_BAIDU_ID:  
      TJ_GOOGLE_ID:  
        
      # 系统通知  
      SYS_NOTIFY:  
        
      # 文件服务器  
      FILE_SERVER:  
        
      # GPT4 调用限制  
      DISABLE_GPT4: "0" # 默认为不禁用GPT4调用  
        
      # Cloudflare R2 存储  
      R2_DOMAIN:  
      R2_BUCKET_NAME:  
      R2_ACCOUNT_ID:  
      R2_KEY_ID:  
      R2_KEY_SECRET:  
        
      # 图片上传设置  
      UPLOAD_IMG_SIZE: "1" # 单位为兆  
        
      # GPT模型配置  
      GPT_URL: "/gpts.json"  
        
      # 主题设置  
      SYS_THEME: "dark"  
        
      # 关闭MD预览  
      CLOSE_MD_PREVIEW: "1"  
        
      # 验证限制  
      AUTH_SECRET_ERROR_COUNT: "3" # 验证错误次数  
      AUTH_SECRET_ERROR_TIME: "10" # 验证错误后停留时间（单位：分钟）